### ISSUE TITLE
发送消息send方法报错

### ISSUE THREAD

**Issue by thinkersOne** [binarywang/weixin-java-mp-demo#103]
exceptionMessage：me.chanjar.weixin.common.error.WxErrorException: 错误代码：43004, 错误信息：需要接收者关注，微信原始报文：{"errcode":43004,"errmsg":"require subscribe rid: 5f99084b-18ab7061-4d169d08"}
  caused by : me.chanjar.weixin.common.error.WxErrorException: 错误代码：43004, 错误信息：需要接收者关注，微信原始报文：{"errcode":43004,"errmsg":"require subscribe rid: 5f99084b-18ab7061-4d169d08"}
stackTrace：
com.chengju.dispatcher.service.DispatcherWXTemplateMessageService.send(DispatcherWXTemplateMessageService.java:89)
com.chengju.dispatcher.service.DispatcherWXTemplateMessageService$$FastClassBySpringCGLIB$$a5f42499.invoke(<generated>)

**Comment by binarywang** [comment]
这错误信息不适合明显吗？

**Comment by thinkersOne** [comment]
但是我没呈现这个错误，我不关注没有报错

**Comment by thinkersOne** [comment]
但是我没呈现这个错误，我以为是没关注&nbsp;公众号导致的，但是实际不是




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "binarywang/weixin-java-mp-demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 下午2:13
收件人:&nbsp;"binarywang/weixin-java-mp-demo"<weixin-java-mp-demo@noreply.github.com&gt;;
抄送:&nbsp;"一直好"<2415612109@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [binarywang/weixin-java-mp-demo] 发送消息send方法报错 (#103)





 
这错误信息不适合明显吗？

**Comment by thinkersOne** [comment]
一般像这种问题我怎么排查呢？
