### ISSUE TITLE
微信send方法报错

### ISSUE THREAD

**Issue by thinkersOne** [binarywang/weixin-java-mp-demo#104]
描述：
微信端老是是不是报这个错，起初我以为是没有关注导致的，但是当我自己取消关注操作时也没有报错，看了微信官网文档没找到相关说明，希望能给出排查这种问题的方法

报错信息如下：
exceptionMessage：me.chanjar.weixin.common.error.WxErrorException: 错误代码：43004, 错误信息：需要接收者关注，微信原始报文：{"errcode":43004,"errmsg":"require subscribe rid: 5f991c84-4d380ee0-002e2cf1"}

  caused by : me.chanjar.weixin.common.error.WxErrorException: 错误代码：43004, 错误信息：需要接收者关注，微信原始报文：{"errcode":43004,"errmsg":"require subscribe rid: 5f991c84-4d380ee0-002e2cf1"}

stackTrace：

com.chengju.dispatcher.service.DispatcherWXTemplateMessageService.send(DispatcherWXTemplateMessageService.java:89)

com.chengju.dispatcher.service.DispatcherWXTemplateMessageService$$FastClassBySpringCGLIB$$a5f42499.invoke(<generated>)

**Comment by binarywang** [comment]
可能是信息不同步导致
