### ISSUE TITLE
JedisWxRedisOps 不识别子类JedisPool

### ISSUE THREAD

**Issue by stellarfan** [binarywang/weixin-java-mp-demo#106]
![image](https://user-images.githubusercontent.com/35050787/99939386-ea140880-2da4-11eb-9d73-bb1c039c29ef.png)

**Comment by stellarfan** [comment]
3.9.0

**Comment by binarywang** [comment]
看不到图片，请尽量用文字描述，谢谢

**Comment by stellarfan** [comment]
作者您好： 
import redis.clients.jedis.JedisPool;
if (this.properties.isUseRedis()) {
                        final WxMpProperties.RedisConfig redisConfig = this.properties.getRedisConfig();
                        JedisPool jedisPool = new JedisPool(redisConfig.getHost(), redisConfig.getPort());
                        configStorage = new WxMpRedisConfigImpl(new JedisWxRedisOps(jedisPool), a.getAppId());
 }
这段代码中，JedisWxRedisOps的构造函数不识别jedisPool，idea提示 Required type： Pool  Provided：JedisPool
版本 weixin-common-Java 3.9.0

**Comment by binarywang** [comment]
看起来是jedis版本不对

**Comment by stellarfan** [comment]
好的 我修改下
