### ISSUE TITLE
如何在handle中获得appid

### ISSUE THREAD

**Issue by rongkun888** [binarywang/weixin-java-mp-demo#107]
![image](https://user-images.githubusercontent.com/37428571/101497061-82191100-39a5-11eb-8ec8-c58a5923b1b0.png)

您好，请问呢如何在handle中获得该条消息的appid

如图所示，两个appid，用户关注后，我如何知道，这条关注消息是属于哪一个公众号的

**Comment by binarywang** [comment]
仔细观察message内容，我记得是有个参数是消息发送方的id，也就是appid

**Comment by rongkun888** [comment]
昨晚解决了，准备关掉来着结果电脑没电关机了。。。
![image](https://user-images.githubusercontent.com/37428571/101584799-6bac9d00-3a19-11eb-8140-54e6e5670451.png)

**Comment by rongkun888** [comment]
> 仔细观察message内容，我记得是有个参数是消息发送方的id，也就是appid
昨晚解决了，准备关掉来着结果电脑没电关机了。。。
![image](https://user-images.githubusercontent.com/37428571/101584922-a3b3e000-3a19-11eb-8134-f9571ab29d1b.png)

**Comment by binarywang** [comment]
麻烦不要总是发截图了，有时候看不到
