### ISSUE TITLE
获取菜单列表接口未更新

### ISSUE THREAD

**Issue by hangyuanfu** [binarywang/weixin-java-mp-demo#108]
http请求方式: GET（请使用https协议）https://api.weixin.qq.com/cgi-bin/get_current_selfmenu_info?access_token=ACCESS_TOKEN
目前接口已经更新呢。但是sdk没有更新

**Comment by binarywang** [comment]
请明确更新内容

**Comment by binarywang** [comment]
如果希望问题可以得到修正，请到WxJava项目准确描述问题，谢谢配合！
