### ISSUE TITLE
大佬，新版本能不能兼容旧版本

### ISSUE THREAD

**Issue by hp88yx** [binarywang/weixin-java-mp-demo#110]
从3.0升级到4.0发现好多地方变了，项目要改的地方太多了，(⊙o⊙)…，大佬下次升级版本能不能考虑一下旧版本的支持，(⊙o⊙)…，谢谢大佬，这样子我这种菜鸡就不用改的头痛了。：）

**Comment by binarywang** [comment]
抱歉，给你带来困惑。
但是由于提交代码人员代码质量参差不齐，出现一些不规范的代码，所以为了规范清理以及更方便扩展，所以并没有兼容保留旧的代码。
其实如果你自己的项目并不需要新版本的功能，不建议升级。

**Comment by hp88yx** [comment]
> 抱歉，给你带来困惑。
> 但是由于提交代码人员代码质量参差不齐，出现一些不规范的代码，所以为了规范清理以及更方便扩展，所以并没有兼容保留旧的代码。
> 其实如果你自己的项目并不需要新版本的功能，不建议升级。

大佬，是老马的小程序文档在更新，原先的Service已经不支持新的接口了，然后我在4.0版本能找到新的接口使用方式，虽然原先3.0版本加了一个通用的调用方式，但是比较麻烦，不方便维护。

**Comment by binarywang** [comment]
这种情况，那实在对不住了。
你的版本跨度有点大，确实会存在不少重构，导致你看起来 需要改很多，不过如果你仔细看，其实都很简单，逐个分析，也很快能修复掉

**Comment by hp88yx** [comment]
> 这种情况，那实在对不住了。
> 你的版本跨度有点大，确实会存在不少重构，导致你看起来 需要改很多，不过如果你仔细看，其实都很简单，逐个分析，也很快能修复掉

好的，大佬，正在查看区别。
