### ISSUE TITLE
群发所有用户文本信息，用户能收到信息，但控制台会包空指针异常

### ISSUE THREAD

**Issue by 13612687938** [binarywang/weixin-java-mp-demo#111]
现象：
1、调用群发接口（文本）给所有用户；
2、用户收到信息；
3、springboot后台日志显示发送消息成功；
4、微信进行了回调，并进入了MsgHandler，且wxMessage.getContent();为空。

请问：
疑问1：为什么会出现第4步？
疑问2：如何“取消关键词回复”，即，不回复，return new TextBuilder().build("", wxMessage, weixinService);会抛出异常。

![image](https://user-images.githubusercontent.com/51987247/104092691-9b70ee00-52c0-11eb-8484-910a9589f14a.png)
![image](https://user-images.githubusercontent.com/51987247/104092702-a9267380-52c0-11eb-9e4c-0bc6a11bf33c.png)
![image](https://user-images.githubusercontent.com/51987247/104092710-b6dbf900-52c0-11eb-92c7-590879473fdb.png)
![image](https://user-images.githubusercontent.com/51987247/104092745-f0acff80-52c0-11eb-959e-d16b1735770e.png)

**Comment by binarywang** [comment]
空指针是你自己的问题，很容易定位
