### ISSUE TITLE
是不是依赖weixin-java-mp包之后不用定时刷新accessToken了

### ISSUE THREAD

**Issue by LillyChen** [binarywang/weixin-java-mp-demo#115]
看源码说WxMpService的所有方法都会在access_token过期时调用getAccessToken(boolean forceRefresh)方法，那是不是就是说可以不用定时任务去刷accessToken了

**Comment by binarywang** [comment]
没错

**Comment by zzy7584** [comment]
我有个问题，如果测试环境和生产环境共用的一个公众号，那不就会相互影响了吗？就是两个环境互相accessToken，导致彼此互相失效，麻烦大佬解惑一下

**Comment by binarywang** [comment]
> 我有个问题，如果测试环境和生产环境共用的一个公众号，那不就会相互影响了吗？就是两个环境互相accessToken，导致彼此互相失效，麻烦大佬解惑一下

肯定互相影响的，你需要保证共用，使用redis等方式存储
