### ISSUE TITLE
项目中先配置了小程序后再配置微信公众号模块启动报错

### ISSUE THREAD

**Issue by SiterZzz** [binarywang/weixin-java-mp-demo#117]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-03-20 14:42:44.751 ERROR 8965 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.taike.wisdom.ftp.wechat.WxPortalController required a bean of type 'me.chanjar.weixin.mp.api.WxMpService' that could not be found.

Action:

Consider defining a bean of type 'me.chanjar.weixin.mp.api.WxMpService' in your configuration.

Process finished with exit code 1

**Comment by binarywang** [comment]
你肯定是少了什么配置
