### ISSUE TITLE
公众号订阅后可以自动回复带小程序跳转链接的消息吗

### ISSUE THREAD

**Issue by Xuguozong** [binarywang/weixin-java-mp-demo#119]
WxMpXmlOutMessage.TEXT() 类型的好像不能支持，其他类型好像也不行，有什么好的办法吗？

**Comment by binarywang** [comment]
用客服消息接口发

**Comment by Xuguozong** [comment]
嗯，昨天晚上也找到了，感谢您的及时回复！

**Comment by jacktang** [comment]
@Xuguozong 能具体说下怎么实现的吗？遇到同样的问题

**Comment by Xuguozong** [comment]
> @Xuguozong 能具体说下怎么实现的吗？遇到同样的问题

// 发送客服消息
WxMpKefuService kefuService = wxMpService.getKefuService();
kefuService.sendKefuMessage(WxMpKefuMessage.TEXT()
           .toUser(openId)
           .content(content())
           .build());
