### ISSUE TITLE
redis 配置的问题

### ISSUE THREAD

**Issue by shaohongwu** [binarywang/weixin-java-mp-demo#120]
wx:
  mp:
    useRedis: true
    redisConfig:
      host: 127.0.0.1
      port: 6379

我使用这个配置发现redis 一直有问题，最后跟踪发下是 WxMpConfiguration.java  有问题，
timeout设置为-1，JedisPool 里面的connectionTimeout 也是-1, 导致一直不能使用：
 connect: timeout can't be negative

![a960d896805064120bc3bf7f0e5c869](https://user-images.githubusercontent.com/39219403/122042020-33dd4280-ce0c-11eb-8d9d-1752e81a2d19.png)

**Comment by binarywang** [comment]
自己更改即可

**Comment by binarywang** [comment]
已更新
