### ISSUE TITLE
使用redis报错  

### ISSUE THREAD

**Issue by hlwskgypmb** [binarywang/weixin-java-mp-demo#121]
`Could not get a resource from the pool
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool

wx:
  mp:
    useRedis: true
    redisConfig:
      host: 127.0.0.1
      port: 6379
      timeout: 2000`

**Comment by binarywang** [comment]
看起来像是redis连接不上的问题？

**Comment by BrockDW** [comment]
需要在本地或者服务器安装Redis，然后才能运行，如果是windows的话需要安装WSL
linux command: `sudo apt install redis-server`
centos command 会不一样： `sudo dnf install redis nano`
