### ISSUE TITLE
找不到 WxMpInMemoryConfigStorage

### ISSUE THREAD

**Issue by william-abel** [binarywang/weixin-java-mp-demo#122]
在项目配置 WxMp AppId时找不到 WxMpInMemoryConfigStorage.class 类
![image](https://user-images.githubusercontent.com/45378809/123510737-bc32d180-d6af-11eb-99ce-c8a45d7a1266.png)
![image](https://user-images.githubusercontent.com/45378809/123510742-c785fd00-d6af-11eb-8004-97ea97c754c3.png)

**Comment by binarywang** [comment]
看wxjava 的 wiki，已重构
