### ISSUE TITLE
wx:configs通过数据库来动态配置

### ISSUE THREAD

**Issue by zenpignoy** [binarywang/weixin-java-mp-demo#124]
wx:
  mp:
    useRedis: false
    redisConfig:
      host: 127.0.0.1
      port: 6379
      timeout: 2000
    configs:
      - appId: 1111 # 第一个公众号的appid
        secret: 1111 # 公众号的appsecret
        token: 111 # 接口配置里的Token值
        aesKey: 111 # 接口配置里的EncodingAESKey值
      - appId: 2222 # 第二个公众号的appid，以下同上
        secret: 1111
        token: 111
        aesKey: 111

wx:configs的配置可以通过数据库来动态加载嘛？

**Comment by hrj5032188** [comment]
https://github.com/binarywang/weixin-java-mp-demo/issues/92

**Comment by binarywang** [comment]
参考楼上所述即可
