### ISSUE TITLE
weixin-java-mp:4.2.1.B 微信发布能力接口文章信息缺少thumb_url字段

### ISSUE THREAD

**Issue by xujijie** [binarywang/weixin-java-mp-demo#126]
微信发布能力的 文章列表接口”https://api.weixin.qq.com/cgi-bin/freepublish/batchget?access_token=ACCESS_TOKEN“和artile_id获取发布文章接口”https://api.weixin.qq.com/cgi-bin/freepublish/getarticle?access_token=ACCESS_TOKEN“的返回信息中却少了thumb_url字段，微信的文档中没有显示此字段，但是实际返回信息中存在，能否添加上。

**Comment by binarywang** [comment]
请到WxJava中提此问题，或者直接在WxJava中提交PR代码

**Comment by binarywang** [comment]
另外你都没有发出具体的报文，即使相加也不知道加哪儿，麻烦明确一下
