### ISSUE TITLE
图文群发api  me.chanjar.weixin.mp.api.WxMpMassMessageService#massGroupMessageSend

### ISSUE THREAD

**Issue by dongdongxiaozi** [binarywang/weixin-java-mp-demo#127]
me.chanjar.weixin.mp.util.json.WxMpMassTagMessageGsonAdapter 
59行代码:
 messageJson.addProperty("send_ignore_reprint", message.isSendIgnoreReprint() ? 0 : 1);  这个结果好像设置反了,  4.2.0 还有这个问题

**Comment by binarywang** [comment]
看最新测试版，已经修复了

**Comment by dongdongxiaozi** [comment]
> 看最新测试版，已经修复了

还有就是草稿箱的  获取草稿信息相关的那些方法返回的字段 也不全,目前4.2.0版本的我是使用post请求自己转换参数的

**Comment by dongdongxiaozi** [comment]
> 看最新测试版，已经修复了

好的 辛苦作者了

**Comment by binarywang** [comment]
有问题请在wxjava里提吧，关于sdk的问题
