### ISSUE TITLE
大佬！！！调用getUserInfo之后出现了个bug

### ISSUE THREAD

**Issue by JasonLonglong** [binarywang/weixin-java-mp-demo#148]
我调用了图中的这个API，然后传入对应的参数，得到的返回值是一个WxMaUserInfo这个实体类的类型的一个对象，该对象可以使用getter去获取值，并且该值为String类型，所以我就用了String的变量去接收该值，但是却报错：Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $，所以无奈之下我就使用了Object的变量去接收该值了，这个是bug还是不应该这么写？
![image](https://github.com/binarywang/weixin-java-mp-demo/assets/67433007/2e706168-1605-4ac2-8b2b-af96c5d6ad52)

**Comment by JasonLonglong** [comment]
DEBUG发现对密文进行解密后获取到的时一串乱码，
![image](https://github.com/binarywang/weixin-java-mp-demo/assets/67433007/1ac95c0f-5ade-4e7e-9b26-6bfe47cf6cd8)

**Comment by JasonLonglong** [comment]
大家开发前一定要去看看开发文档首页的常见问题（自己踩了半天坑才想起来这个），我这个就是微信小程序的login跟getUserInfo两个API调用顺序不对产生的问题，要先调用login之后再调用getUserInfo.

**Comment by binarywang** [comment]
你这不是小程序的问题吗，为啥写到了这里

**Comment by JasonLonglong** [comment]
> 你这不是小程序的问题吗，为啥写到了这里

抱歉，注意到，写错地方了，但是问题解决了，嘿嘿。
