### ISSUE TITLE
Consider defining a bean of type 'me.chanjar.weixin.mp.api.WxMpService' in your configuration.

### ISSUE THREAD

**Issue by artFollower** [binarywang/weixin-java-mp-demo#149]
Description:

Parameter 1 of constructor in com.ruoyi.wx.controller.WxUserController required a bean of type 'me.chanjar.weixin.mp.api.WxMpService' that could not be found.

Action:

Consider defining a bean of type 'me.chanjar.weixin.mp.api.WxMpService' in your configuration.

**Comment by binarywang** [comment]
先把demo跑起来，然后再看为什么你自己的项目会报错

**Comment by artFollower** [comment]
好了，是lombok 只引入到模块，没有在整个项目里面引入导致的
