### ISSUE TITLE
公众号地址配置成功后，后台无法接收到平台发送的消息

### ISSUE THREAD

**Issue by gaozhangithubaccount** [binarywang/weixin-java-mp-demo#76]
@binarywang   @@我第一基于微信公众平台开发，今天我把demo导入后，配置的信息都是成功的，但是发送信息后台却接收不到xml消息，是哪里出问题？

**Comment by binarywang** [comment]
服务器域名问题，看哪里不合要求？

**Comment by pendyliu** [comment]
我也是出现了同样的问题，用的netapp内网穿透，控制台打印出来：接收到来自微信服务器的认证消息，我往公众号里面发消息后台不响应，不知为何？不知道一楼兄弟好了没？ @gaozhangithubaccount

**Comment by dclog** [comment]
1.服务器配置 是否启用
2.要将自己服务器的IP添加到IP白名单，否则微信会将你的消息过滤掉。
