### ISSUE TITLE
jsapiticket获取为null

### ISSUE THREAD

**Issue by wzq530897296** [binarywang/weixin-java-mp-demo#85]
wxService.getJsapiTicket();只有在项目启动的第一次有值，我加的定时任务，之后获取的值都是null。
在源码里面，wxMpConfigStorage.isJsapiTicketExpired()；空指针异常。

**Comment by wzq530897296** [comment]
我放在缓存中，2小时不到执行一次。过了这个时间。会获取不到。是因为没有刷新token的缘故吗。那我在这个函数中也执行wxService.getAccessToken(true)；可以吗？

**Comment by binarywang** [comment]
空指针异常很容易定位原因，源码都在那里的，自己分析下是哪个对象没有实例化？
